const mongoose = require('mongoose');

const querySchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  dataset: { type: mongoose.Schema.Types.ObjectId, ref: 'Dataset', required: true },
  prompt: { type: String, required: true },
  chartConfig: { type: mongoose.Schema.Types.Mixed }, // JSON generated by LLM
  resultData: [{ type: mongoose.Schema.Types.Mixed }], // Aggregated result
  errorMessage: { type: String }
}, { timestamps: true });

module.exports = mongoose.model('Query', querySchema);
